"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.85KB] > /home/adrian/Downloads/lego_gandalf/scene-transformed.glb [148.82KB] (-2968%)
Author: Tirto Suwondo (https://sketchfab.com/Tirto.Suwondo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lego-gandalf-d2ef331c52544c17b7d31674d833174b
Title: Lego Gandalf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Gandalf(props) {

  const { nodes, materials } = useGLTF('/models/lego-gandalf-transformed.glb')

  const modelRef = useRef();
  useFrame((state, delta, xrFrame) => {

    modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.y += 0.01 * Math.sin(state.clock.elapsedTime) * 0.15;

  })
  return (
    <group {...props} dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[2, 2, 2]}
      rotation={[-0.05, -0.29, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gandalf_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/lego-gandalf-transformed.glb')