import { Inter } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import FireFliesBackground from './components/FireFliesBackground';
import Sound from './components/Sound';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: 'Adrian Cubillos - Portfolio ',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={clsx(inter.variable, 'bg-background text-foreground font-inter')}>
        {children}
        <FireFliesBackground />
        <Sound />
        <div id="my-modal" className="z-[9999] fixed inset-0 pointer-events-none"></div>
      </body>
    </html>
  );
}
